Add edit profile and change password forms
MarcusTXK/Swappee pull request #16
Opened 2021-12-23 09:46 UTC by tyh3818

# Description
Added edit profile and change password forms on the profile page

## Type of change
- [X] New feature (non-breaking change which adds functionality)

# Screenshot
![profile](https://user-images.githubusercontent.com/68331979/147221926-3e5b99c9-1333-4be3-bdb0-3bb748487c1d.gif)

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings

2021-12-24 04:49 UTC, MarcusTXK requested changes
Wow, really good job! Looks really good.  Just some minor changes and it can be merged.

Some things to note:
Please use the thinner versions for the inputs (pass the prop `size="small"`) as the current ones are very thick. Also be mindful when editing shared components, such as changing their heights, as it breaks other components as seen here in the login modal, where the inputs are now of different sizes:
![image](https://user-images.githubusercontent.com/50147457/147316835-c558af67-6f2b-4c09-930e-b4a31503d56c.png)

Run `yarn lint` and `yarn build` and try to resolve all the errors
![image](https://user-images.githubusercontent.com/50147457/147317179-236342da-327f-4bae-b302-068c8c0762a9.png)

2021-12-24 04:49 UTC, MarcusTXK commented on frontend/components/molecules/MProfilePhoto.tsx
> +        <Image src={profilePicture} alt="profile picture" />
Update the src to either use the avatar from the backend or to use dicebear's randomly generated profile picture based on their username.

src={avatar || `https://avatars.dicebear.com/api/bottts/${username}.svg`}

2021-12-24 04:49 UTC, MarcusTXK commented on frontend/components/organisms/OChangePasswordForm.tsx
> +  const [confirmPass, setConfirmPass] = useState('');
Add validation when they submit to check if these two are the same, if not warn the user. You can refer to `OLoginDialog`.

2021-12-24 04:49 UTC, MarcusTXK commented on frontend/pages/profile.tsx
> +  };
Consider using CamelCase for the values.

2021-12-24 16:17 UTC, tyh3818 commented
I have added the validation to check if the new password is the same as the confirm password. I have also changed to input text boxes size to small and changed the logo such that it displays the image that was uploaded(or the randomly generated image if no file has been uploaded yet).

2022-01-06 11:22 UTC, MarcusTXK approved these changes
LGTM, great job!

2022-01-06 11:22 UTC, merged